[build]
    command = "npm run build"
    publish = "/build"
    base = "/"
    functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200